### PR TITLE
Fix: MPQs > 2GB fail to load

### LINKED ISSUE #28: Bug: MPQs > 2GB fail to load
This appears to be two issues:

**Incorrect llseek behavior when seeking `>= 2 ** 31`**

These lines in the emscripten FS layer do not play well with offsets beyond `2 ** 31` bytes.

```js
var stream = SYSCALLS.getStreamFromFD(), offset_high = SYSCALLS.get(), offset_low = SYSCALLS.get(), result = SYSCALLS.get(), whence = SYSCALLS.get();
// NOTE: offset_high is unused - Emscripten's off_t is 32-bit
var offset = offset_low;
FS.llseek(stream, offset, whence);
```

`offset_low` is read as a signed integer out of `HEAP32` by `SYSCALLS.get()`. As a result, the value wraps after exceeding `2,147,483,647` bytes, even though it's not surprising to seek past that limit when working with large files.

**Runtime assert intersecting with incompatible types**

This line in `SBaseFileTable.cpp` fails, despite the values matching:

```cpp
assert(pHeader->BlockTableSize64 <= (pHeader->dwBlockTableSize * sizeof(TMPQBlock)));
```

Presumably, some combination of the types of `pHeader->BlockTableSize64`, `pHeader->dwBlockTableSize`, and `sizeof(TMPQBlock)` prevent the assert's equality comparison from returning true.

### PR DESCRIPTION
**Pull request by fallenoak**
This fixes two issues with MPQs `>= 2 ** 31` bytes:

- The debug version of StormLib is compiled using CMake's release build type. This prevents some runtime asserts from misbehaving.

- The `llseek` syscall (`___syscall140`) is replaced by a version that works around seeking to offsets `>= 2 ** 31` bytes. This workaround will remain necessary until emscripten starts to use 64-bit integers for seeking offsets.

Closes #28

### CODE REVIEW

File: src/binding/post.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+    // If whence is SEEK_SET, assume the value cannot be negative. This permits
+    // SEEK_SET to seek to offsets >= 2 ** 31 and <= 2 ** 32.
+    //
+    // This workaround does *not* account for cases where offsets used with
+    // SEEK_CUR or SEEK_END are >= 2 ** 31. Such cases will produce unexpected
+    // behavior.
+    var offset = whence === 0 ? offset_low >>> 0 : offset_low;
+
+    FS.llseek(stream, offset, whence);
+    HEAP32[((result)>>2)]=stream.position;
```
Comment (timkurvers) [inline src/binding/post.js:19]: The bitwise shift and the assignment could use a bit more breathing space.

**Review by timkurvers — APPROVED** [review]
Looks good to me!

The `___syscall140` function is overriding the actual implementation, right? Would it be a good idea to link to the original in a comment or something?

File: src/binding/post.js (hunk 1 above)
Comment (fallenoak) [reply src/binding/post.js:19]: I tried to make minimal changes to the original implementation of `___syscall140` here.
